"""Creacion inicial

Revision ID: 3f3023e52404
Revises: 
Create Date: 2026-06-21 14:24:27.062297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f3023e52404'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empleado')
    op.drop_table('especialista')
    op.drop_table('usuario')
    op.drop_table('cita')
    op.drop_table('especializacion')
    with op.batch_alter_table('rol', schema=None) as batch_op:
        batch_op.alter_column('nombre_rol',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rol', schema=None) as batch_op:
        batch_op.alter_column('nombre_rol',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    op.create_table('especializacion',
    sa.Column('id_especializacion', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre_especializacion', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_especializacion', name=op.f('especializacion_pkey'))
    )
    op.create_table('cita',
    sa.Column('id_cita', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha_cita', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('hora_cita', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('id_empleado', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_empleado_especialista', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estado_cita', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleado.id_empleado'], name=op.f('cita_id_empleado_fkey')),
    sa.ForeignKeyConstraint(['id_empleado_especialista'], ['especialista.id_empleado'], name=op.f('cita_id_empleado_especialista_fkey')),
    sa.PrimaryKeyConstraint('id_cita', name=op.f('cita_pkey'))
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('clave', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('id_empleado', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_rol', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleado.id_empleado'], name=op.f('usuario_id_empleado_fkey')),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id_rol'], name=op.f('usuario_id_rol_fkey')),
    sa.PrimaryKeyConstraint('id_usuario', name=op.f('usuario_pkey'))
    )
    op.create_table('especialista',
    sa.Column('id_empleado', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_especializacion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hora_inicio', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('hora_fin', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('dias_disponibles', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleado.id_empleado'], name=op.f('especialista_id_empleado_fkey')),
    sa.ForeignKeyConstraint(['id_especializacion'], ['especializacion.id_especializacion'], name=op.f('especialista_id_especializacion_fkey')),
    sa.PrimaryKeyConstraint('id_empleado', name=op.f('especialista_pkey'))
    )
    op.create_table('empleado',
    sa.Column('id_empleado', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cedula', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('nombres', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('apellidos', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('correo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_empleado', name=op.f('empleado_pkey'))
    )
    # ### end Alembic commands ###
